name: agconnect_crash
description: Flutter plugin for AppGallery Connect Crash SDK.
version: 1.6.0+300
homepage: https://developer.huawei.com/consumer/cn/doc/development/AppGallery-connect-Guides/agc-crash-introduction

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=3.3.9"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agconnectcrash
        pluginClass: AGConnectCrashPlugin
      ios:
        pluginClass: AGConnectCrashPlugin
