name: innim_agconnect_crash
description: Flutter plugin for AppGallery Connect Crash SDK.
version: 1.7.0
homepage: https://developer.huawei.com/consumer/cn/doc/development/AppGallery-connect-Guides/agc-crash-introduction
repository: https://github.com/Innim/innim_agconnect_crash
issue_tracker: https://github.com/Innim/innim_agconnect_crash_facebook/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agconnectcrash
        pluginClass: AGConnectCrashPlugin
      ios:
        pluginClass: AGConnectCrashPlugin
